import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { BoardProvider } from "@/context/myContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <BoardProvider>
        <body className={inter.className}>{children}</body>
      </BoardProvider>
    </html>
  );
}
